Address conflict between clang in osxcross and what latest MacOS SDK
go-gl/glfw3 pull request #367
Opened 2022-10-18 23:38 UTC by Bluebugs

Latest MacOS SDK is using an attribute that confuse the clang provided by osxcross. As this attribute is just going to generate a warning at build time and seems to be of low value, getting rid of it seems like the easiest path forward that I can think of.

2022-10-18 23:39 UTC, Bluebugs commented
Not to sure if this would be the logical way to go at this problem for the go-glfw project. Let me know if you can think of an alternate solution.

2022-10-19 06:01 UTC, Jacalz commented
Is this perhaps something that should be added to upstream glfw instead? Seems like something that could affect them as well

2022-10-19 06:03 UTC, Jacalz requested changes

2022-10-19 06:03 UTC, Jacalz commented on v3.1/glfw/glfw/src/internal.h
> +#define NS_FORMAT_ARGUMENT(A)
Per my previous comment, this is a file synced with upstream glfw releases. We likely wasn't to add this upstream instead

2022-10-20 00:15 UTC, Bluebugs commented
Upgrading to llvm v14 solve the problem. It is easier than maintaining this patch. Abandoning it then.

2022-10-20 00:15 UTC, closed without merging