Remove warning/errors about undefined functions
go-gl/glfw3 pull request #399
Opened 2024-04-23 22:13 UTC by metal3d

see #359

features.h needs `_GNU_SOURCE` to be set to allow stdlib.h to declare the functions.

2024-04-23 22:17 UTC, metal3d commented
fixes #359

2024-04-23 22:38 UTC, dmitshur approved these changes, later dismissed
Seems okay to me.

We had this in v3.2 but didn't propagate it forward to v3.3:

https://github.com/go-gl/glfw/blob/a69d953ea14231b2f19998f0b434b6c1e6c6f710/v3.2/glfw/build.go#L25-L26

(It was added there in #212 and 691ee1b84c51ae625ed1aafebc915d3db3d63d66.)

Thanks. Giving a chance to @Jacalz to also take a look.

2024-04-24 08:40 UTC, Jacalz requested changes
Thanks. I am however getting this warning on both X11 and Wayland compilations on Fedora Silverblue 39. Is there any way that we can avoid getting warnings about multiple definitions?
```
# github.com/go-gl/glfw/v3.3/glfw
In file included from ../../c_glfw_lin.go:10:
../../glfw/src/wl_window.c:29:9: warning: "_GNU_SOURCE" redefined
   29 | #define _GNU_SOURCE
      |         ^~~~~~~~~~~
<command-line>: note: this is the location of the previous definition
```
Could it be that the file that previously was giving the warnings should have a `#define _GNU_SOURCE` instead and these build changes should be removed?

EDIT: I tried my suggested fix and it does not seem to improve anything :(

2024-04-24 18:16 UTC, dmitshur reviewed
Looking more, I found we removed these from v3.3 in #356 (to fix #351). So I agree it seems this needs more investigation. Also see past discussion in https://github.com/glfw/glfw/issues/2133 and https://github.com/glfw/glfw/issues/2076.

2024-04-25 14:46 UTC, Jacalz commented
Hmm. I have one idea. Given that those warnings on Wayland now are errors after the linker changes in Fedora 40 (I've confirmed what @metal3d saw), how about we just enable GNU_SOURCE for Wayland builds?

It's obviously just a short-term fix but it does improve things quite a bit. Anyone using Fedora 40 can then compile the binary (three errors become one warning) and everyone else gets one warning instead of three. Seems like a win until we manage to get all the warnings to disappear?

2024-04-26 05:38 UTC, metal3d commented
I agree @Jacalz, this is critical on Fedora 40 and probably with others distributions that are up to date. Without this fix, it's impossible to build any Fyne application with Wayland support.

A warning isn't problematic as it's only an already defined directive. IMHO this shouldn't be a problem, even if the warning is fixed, later, in the glfw project.

2024-04-26 07:17 UTC, Jacalz commented
Yeah, but given that there is no compilation problem on X11, I see not point in adding a new warning just for the sake of it. Would you mind keeping it enabled only for Wayland?

2024-05-06 07:51 UTC, metal3d commented
FYI, I made the change to only set the directive to compile on Wayland. It is a very important fix that allows Fyne application to compile on Fedora 40.

Even if it's temporary, this fix is highly necessary.

2024-05-06 10:40 UTC, Jacalz approved these changes
Sorry for the late review. I was away running a half-marathon during the weekend. This looks great. Thanks for the fix.

2024-05-06 10:40 UTC, merged